name: Run Selenium Tests

on:
  workflow_dispatch:
    inputs:
      product_id:
        description: 'The ID of the searched product'
        required: true
        default: "GL-D201APZU"
  push:
    branches:
      - main

jobs:
  selenium_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Product ID
        run: echo "searchProductID=${{ inputs.product_id }}" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Run Selenium Tests
        run: mvn test -DsearchProductID="${{ env.searchProductID }}"
